car_name = {
    "PUSMC01": "Hunter CAVALRY Finish 1",
    "PUSMC1A2": "Hunter CAVALRY Finish 2",
    "PUSMC1A3": "Hunter CAVALRY Finish 3",
    "PUSMC0G": "Hunter CAVALRY Finish Gold",
    "PUSMC0C": "Hunter CAVALRY Finish Platinium",
    "XUSM1B1": "OVAL CHAMP 69 Finish 1",
    "XUSM1B2": "OVAL CHAMP 69 Finish 2",
    "XUSM1B3": "OVAL CHAMP 69 Finish 3",
    "XUSM1BG": "OVAL CHAMP 69 Finish Gold",
    "XUSM1BC": "OVAL CHAMP 69 Finish Platinum",
    "PUSCLT02": "Hunter MESQUITE Finish 1",
    "PUSCT2A2": "Hunter MESQUITE Finish 2",
    "PUSCT2A3": "Hunter MESQUITE Finish 3",
    "PUSCLT0G": "Hunter MESQUITE Gold",
    "PUSCLT0C": "Hunter MESQUITE Platinum",
    "XUSLT2B1": "Hunter MESQUITE CUSTOM Finish 1",
    "XUSCT2A2": "Hunter MESQUITE CUSTOM Finish 2",
    "XUSCT2A3": "Hunter MESQUITE CUSTOM Finish 3",
    "XUSLT2BG": "Hunter MESQUITE CUSTOM Gold",
    "XUSLT2BC": "Hunter MESQUITE CUSTOM Platinum",
    "PASBSC01": "Nakamura Finish 1",
    "PASBSCA2": "Nakamura Finish 2",
    "PASBSCA3": "Nakamura SI-7 Finish 3",
    "PASBSC0G": "Nakamura Gold",
    "PASBSC0C": "Nakamura Platinum",
    "XASBSCB1": "Nakamura Finish 1",
    "XASBSCB2": "Nakamura Finish 2",
    "XASBSCB3": "Nakamura RACING SI-7 Finish 3",
    "XASBSCBG": "Nakamura Gold",
    "XASBSCBC": "Nakamura Platinum",
    "PUSCC01": "Hunter VEGAS Finish 1",
    "PUSCCA2": "Hunter VEGAS Finish 2",
    "PUSCCA3": "Hunter VEGAS Finish 3",
    "PUSCC0G": "Hunter VEGAS Gold",
    "PUSCC0C": "Hunter VEGAS Platinum",
    "XUSCCB1": "Hunter VEGAS CARNIVALE Finish 1",
    "XUSCCB2": "Hunter VEGAS CARNIVALE Finish 2",
    "XUSCCB3": "Hunter VEGAS CARNIVALE Finish 3",
    "XUSCCBG": "Hunter VEGAS CARNIVALE Gold",
    "XUSCCBC": "Hunter VEGAS CARNIVALE Platinum",
    "PEUSV01": "Krieger PIONEER Finish 1",
    "PEUSVA2": "Krieger PIONEER Finish 2",
    "PEUSVA3": "Krieger PIONEER Finish 3",
    "PEUSV0G": "Krieger PIONEER Gold",
    "PEUSV0C": "Krieger PIONEER Platinum",
    "XEUSVB1": "Krieger PIONEER SUPER GATOR Finish 1",
    "XEUSVB2": "Krieger PIONEER SUPER GATOR Finish 2",
    "XEUSVB3": "Krieger PIONEER SUPER GATOR Finish 3",
    "XEUSVBG": "Krieger PIONEER SUPER GATOR Gold",
    "XEUSVBC": "Krieger PIONEER SUPER GATOR Platinum",
    "PASBS01": "Nakamura IKUSA GT Finish 1",
    "PASBS1A2": "Nakamura IKUSA GT Finish 2",
    "PASBS1A3": "Nakamura IKUSA GT Finish 3",
    "PASBS0G": "Nakamura IKUSA GT Gold",
    "PASBS0C": "Nakamura IKUSA GT Platinum",
    "XASBSB1": "Nakamura IKUSA SAMURAI Finish 1",
    "XASBS1B2": "Nakamura IKUSA SAMURAI Finish 2",
    "XASBS1B3": "Nakamura IKUSA SAMURAI Finish 3",
    "XASBSBG": "Nakamura IKUSA SAMURAI Gold",
    "XASBSBC": "Nakamura IKUSA SAMURAI Platinum",
    "CARBB1GT": "Nakamura CARBON IKUSA GT",
    "PSPBZ": "Nakamura B'Z IKUSA GT",
    "PASBCC01": "Kitano HYDROS CUSTOM Finish 1",
    "PASBCCA2": "Kitano HYDROS CUSTOM Finish 2",
    "PASBCCA3": "Kitano HYDROS CUSTOM Finish 3",
    "PASBCC0G": "Kitano HYDROS CUSTOM Gold",
    "PASBCC0C": "Kitano HYDROS CUSTOM Platinum",
    "XASBCB1": "Kitano HYDROS TECHNO Finish 1",
    "XASBCB2": "Kitano HYDROS TECHNO Finish 2",
    "XASBCB3": "Kitano HYDROS TECHNO Finish 3",
    "XASBCBG": "Kitano HYDROS TECHNO Gold",
    "XASBCBC": "Kitano HYDROS TECHNO Platinum",
    "CARBB2CC": "Kitano CARBON HYDROS CUSTOM",
    "PSPYODO": "Kitano YODOBASHI CUSTOM",
    "PSPMICR": "Kitano MICROMANIA CUSTOM",
    "PUSCT01": "Hunter RELIABLE CUSTOM Finish 1",
    "PUSCT1A2": "Hunter RELIABLE CUSTOM Finish 2",
    "PUSCT1A3": "Hunter RELIABLE CUSTOM Finish 3",
    "PUSCT0G": "Hunter RELIABLE CUSTOM Gold",
    "PUSCT0C": "Hunter RELIABLE CUSTOM Platinum",
    "XUSCT01B": "Hunter RELIABLE SPECIAL Finish 1",
    "XUSCT1B2": "Hunter RELIABLE SPECIAL Finish 2",
    "XUSCT1B3": "Hunter RELIABLE SPECIAL Finish 3",
    "XUSCT01G": "Hunter RELIABLE SPECIAL Gold",
    "XUSCT01C": "Hunter RELIABLE SPECIAL Platinum",
    "PSPTS": "Hunter TILLY'S CUSTOM",
    "PEUBR01": "Watson R-TURBO ROADSTER Finish 1",
    "PEUBRA2": "Watson R-TURBO ROADSTER Finish 2",
    "PEUBRA3": "Watson R-TURBO ROADSTER Finish 3",
    "PEUBR0G": "Watson R-TURBO ROADSTER Gold",
    "PEUBR0C": "Watson R-TURBO ROADSTER Platinum",
    "XEUBRB": "Watson BURNOUT ROADSTER Finish 1",
    "XEUBRB2": "Watson BURNOUT ROADSTER Finish 2",
    "XEUBRB3": "Watson BURNOUT ROADSTER Finish 3",
    "XEUBRG": "Watson BURNOUT ROADSTER Gold",
    "XEUBRC": "Watson BURNOUT ROADSTER Platinum",
    "PEULM01": "Rossolini LM CLASSIC Finish 1",
    "PEULMA2": "Rossolini LM CLASSIC Finish 2",
    "PEULMA3": "Rossolini LM CLASSIC Finish 3",
    "PEULM0G": "Rossolini LM CLASSIC Gold",
    "PEULM0C": "Rossolini LM CLASSIC Platinum",
    "XEULM1B1": "Rossolini LM TRACK PACKAGE Finish 1",
    "XEULMB2": "Rossolini LM TRACK PACKAGE Finish 2",
    "XEULMB3": "Rossolini LM TRACK PACKAGE Finish 3",
    "XEULM1BG": "Rossolini LM TRACK PACKAGE Gold",
    "XEULM1BC": "Rossolini LM TRACK PACKAGE Platinum",
    "PUSBC01": "Hunter MANHATTAN Finish 1",
    "PUSBCA2": "Hunter MANHATTAN Finish 2",
    "PUSBCA3": "Hunter MANHATTAN Finish 3",
    "PUSBC0G": "Hunter MANHATTAN Gold",
    "PUSBC0C": "Hunter MANHATTAN Platinum",
    "XUSBCB1": "Hunter MANHATTAN CUSTOM Finish 1",
    "XUSBCB2": "Hunter MANHATTAN CUSTOM Finish 2",
    "XUSBCB3": "Hunter MANHATTAN CUSTOM Finish 3",
    "XUSBCBG": "Hunter MANHATTAN CUSTOM Gold",
    "XUSBCBC": "Hunter MANHATTAN CUSTOM Platinum",
    "PUSM03": "Carson FASTBACK Finish 1",
    "PUSM3A2": "Carson FASTBACK Finish 2",
    "PUSM3A3": "Carson FASTBACK Finish 3",
    "PUSM0G": "Carson FASTBACK Gold",
    "PUSM0C": "Carson FASTBACK Platinum",
    "XUSMU3B": "Carson FASTBACK SPECIAL Finish 1",
    "XUSM3B2X": "Carson FASTBACK SPECIAL Finish 2",
    "XUSM3B3X": "Carson FASTBACK SPECIAL Finish 3",
    "XUSM3G": "Carson FASTBACK SPECIAL Gold",
    "XUSM3C": "Carson FASTBACK SPECIAL Platinum",
    "PUSGA01": "Carson GRAND MARAIS Finish 1",
    "PUSGA1A2": "Carson GRAND MARAIS Finish 2",
    "PUSGA1A3": "Carson GRAND MARAIS Finish 3",
    "PUSGA0G": "Carson GRAND MARAIS Gold",
    "PUSGA0C": "Carson GRAND MARAIS Platinum",
    "PUSGAB1": "Carson GRAND SICILIAN Finish 1",
    "PUSGAB2": "Carson GRAND SICILIAN Finish 2",
    "PUSGAB3": "Carson GRAND SICILIAN Finish 3",
    "PUSGABG": "Carson GRAND SICILIAN Gold",
    "PUSGABC": "Carson GRAND SICILIAN Platinum",
    "PEUSR01": "Montgomery HYPERION Finish 1",
    "PEUSRA2": "Montgomery HYPERION Finish 2",
    "PEUSRA3": "Montgomery HYPERION Finish 3",
    "PEUSR0G": "Montgomery HYPERION Gold",
    "PEUSR0C": "Montgomery HYPERION Platinum",
    "XEUSRB1": "Montgomery HYPERION RATTLER Finish 1",
    "XEUSRB2": "Montgomery HYPERION RATTLER Finish 2",
    "XEUSRB3": "Montgomery HYPERION RATTLER Finish 3",
    "XEUSRBG": "Montgomery HYPERION RATTLER Gold",
    "XEUSRBC": "Montgomery HYPERION RATTLER Platinum",
    "PEUSC03": "Krieger 616 SPORT Finish 1",
    "PEUS3A2": "Krieger 616 SPORT Finish 2",
    "PEUS3A3": "Krieger 616 SPORT Finish 3",
    "PEUSC0G": "Krieger 616 SPORT Gold",
    "PEUSC0C": "Krieger 616 SPORT Platinum",
    "XEUSC3B1": "Krieger 616 ARACHNO SPORT Finish 1",
    "XEUSC3B2": "Krieger 616 ARACHNO SPORT Finish 2",
    "XEUSC3B3": "Krieger 616 ARACHNO SPORT Finish 3",
    "XEUSC3BG": "Krieger 616 ARACHNO SPORT Gold",
    "XEUSC3BC": "Krieger 616 ARACHNO SPORT Platinum",
    "PUSME01": "Hunter SPUR Finish 1",
    "PUSMEA2": "Hunter SPUR Finish 2",
    "PUSMEA3": "Hunter SPUR Finish 3",
    "PUSME0G": "Hunter SPUR Gold",
    "PUSME0C": "Hunter SPUR Platinum",
    "XUSMEB1": "Hunter HOTSPUR Finish 1",
    "XUSMEB2": "Hunter HOTSPUR Finish 2",
    "XUSMEB3": "Hunter HOTSPUR Finish 3",
    "XUSMEBG": "Hunter HOTSPUR Gold",
    "XUSMEBC": "Hunter HOTSPUR Platinum",
    "PEURC03": "Montgomery GT 2400 Finish 1",
    "PEUR3A2": "Montgomery GT 2400 Finish 2",
    "PEUR3A3": "Montgomery GT 2400 Finish 3",
    "PEURC0G": "Montgomery GT 2400 Gold",
    "PEURC0C": "Montgomery GT 2400 Platinum",
    "XEURC3B1": "Montgomery SABOTAGE GT 2400 Finish 1",
    "XEUR3B2": "Montgomery SABOTAGE GT 2400 Finish 2",
    "XEUR3B3": "Montgomery SABOTAGE GT 2400 Finish 3",
    "XEURC3BG": "Montgomery SABOTAGE GT 2400 Gold",
    "XEURC3BC": "Montgomery SABOTAGE GT 2400 Platinum",
    "PUSSC01": "Jansen P12 Finish 1",
    "XUSSCA2": "Jansen P12 Finish 2",
    "PUSSCA3": "Jansen P12 Finish 3",
    "PUSSC0G": "Jansen P12 Gold",
    "PUSSC0C": "Jansen P12 Platinum",
    "XUSSCB1": "Jansen P12 TRACK PACKAGE Finish 1",
    "XUSSCB2": "Jansen P12 TRACK PACKAGE Finish 2",
    "XUSSCB3": "Jansen P12 TRACK PACKAGE Finish 3",
    "XUSSCBG": "Jansen P12 TRACK PACKAGE Gold",
    "XUSSCBC": "Jansen P12 TRACK PACKAGE Platinum",
    "PUSCV01": "Carson INFERNO VAN Finish 1",
    "PUSCV1A2": "Carson INFERNO VAN Finish 2",
    "PUSCV1A3": "Carson INFERNO VAN Finish 3",
    "PUSCV0G": "Carson INFERNO VAN Gold",
    "PUSCV0C": "Carson INFERNO VAN Platinum",
    "PDLCCVFA": "Carson HIPPY VAN Finish 1",
    "PDLCCVL2": "Carson HIPPY VAN Finish 2",
    "PDLCCVL3": "Carson HIPPY VAN Finish 3",
    "XUSCV1B1": "Carson INFERNO BRT VAN Finish 1",
    "XUSCV1B2": "Carson INFERNO BRT VAN Finish 2",
    "XUSCV1B3": "Carson INFERNO BRT VAN Finish 3",
    "XUSCV1BG": "Carson INFERNO BRT VAN Gold",
    "XUSCV1BC": "Carson INFERNO BRT VAN Platinum",
    "PEUSC02": "Rossolini TEMPESTA Finish 1",
    "PEUS2A2": "Rossolini TEMPESTA Finish 2",
    "PEUS2A3": "Rossolini TEMPESTA Finish 3",
    "PEUSC02G": "Rossolini TEMPESTA Gold",
    "PEUSC02C": "Rossolini TEMPESTA Platinum",
    "PBTRT01": "Rossolini TEMPESTA DREAM Finish 1",
    "PBTRT0B": "Rossolini TEMPESTA DREAM Finish 2",
    "PBTRT0C": "Rossolini TEMPESTA DREAM Finish 3",
    "XEUSC2B": "Rossolini TEMPESTA GT Finish 1",
    "XEUSC2B2": "Rossolini TEMPESTA GT Finish 2",
    "XEUSC2B3": "Rossolini TEMPESTA GT Finish 3",
    "XEUSC2G": "Rossolini TEMPESTA GT Gold",
    "XEUSC2C": "Rossolini TEMPESTA GT Platinum",
    "PUSLR01": "Carson OPUS Finish 1",
    "PUSLR1A2": "Carson OPUS Finish 2",
    "PUSLR1A3": "Carson OPUS Finish 3",
    "PUSLR0G": "Carson OPUS Gold",
    "PUSLR0C": "Carson OPUS Platinum",
    "XUSLRB1": "Carson OPUS XS Finish 1",
    "XUSLRB2": "Carson OPUS XS Finish 2",
    "XUSLRB3": "Carson OPUS XS Finish 3",
    "XUSLRBG": "Carson OPUS XS Gold",
    "XUSLRBC": "Carson OPUS XS Platinum",
    "PUSMC02": "Carson ANNIHILATOR Finish 1",
    "PUSM2A2": "Carson ANNIHILATOR Finish 2",
    "PUSM2A3": "Carson ANNIHILATOR Finish 3",
    "PUSM02G": "Carson ANNIHILATOR Gold",
    "PUSM02C": "Carson ANNIHILATOR Platinum",
    "XUSM2B1": "Carson ANNIHILATOR PHOENIX Finish 1",
    "XUSM2B2": "Carson ANNIHILATOR PHOENIX Finish 2",
    "XUSM2B3": "Carson ANNIHILATOR PHOENIX Finish 3",
    "XUSM2BG": "Carson ANNIHILATOR PHOENIX Gold",
    "XUSM2BC": "Carson ANNIHILATOR PHOENIX Platinum",
    "PEUSC04": "Jansen X12 Finish 1",
    "PEUS4A2": "Jansen X12 Finish 2",
    "PEUS4A3": "Jansen X12 Finish 3",
    "PEUSC04G": "Jansen X12 Gold",
    "PEUSC04S": "Jansen X12 Platinum",
    "PEUS4B1": "Jansen XS12 Finish 1",
    "PEUS4B2": "Jansen XS12 Finish 2",
    "PEUS4B3": "Jansen XS12 Finish 3",
    "PEUS4BG": "Jansen XS12 Gold",
    "PEUS4BC": "Jansen XS12 Platinum",
    "CARBSC04": "Jansen CARBON X12",
    "PASC01": "Kitano TOUGE SPORT Finish 1",
    "PASC1A2": "Kitano TOUGE SPORT Finish 2",
    "PASC1A3": "Kitano TOUGE SPORT Finish 3",
    "PASC0G": "Kitano TOUGE SPORT Gold",
    "PASC0C": "Kitano TOUGE SPORT Platinum",
    "XASC1B1": "Kitano TOUGE CRITERION Finish 1",
    "XASC1B2": "Kitano TOUGE CRITERION Finish 2",
    "XASC1B3": "Kitano TOUGE CRITERION Finish 3",
    "XASC1BG": "Kitano TOUGE CRITERION Gold",
    "XASC1BC": "Kitano TOUGE CRITERION Platinum",
    "PSPGAS": "Kitano GAMESTOP SPORT",
    "PUSPK01": "Hunter TAKEDOWN 4X4 Finish 1",
    "PUSPKA2": "Hunter TAKEDOWN 4X4 Finish 2",
    "PUSPKA3": "Hunter TAKEDOWN 4X4 Finish 3",
    "PUSPK0G": "Hunter TAKEDOWN 4X4 Gold",
    "PUSPK0C": "Hunter TAKEDOWN 4X4 Platinum",
    "XUSPKB1": "Hunter TAKEDOWN DIRT RACER Finish 1",
    "XUSPKB2": "Hunter TAKEDOWN DIRT RACER Finish 2",
    "XUSPKB3": "Hunter TAKEDOWN DIRT RACER Finish 3",
    "XUSPKBG": "Hunter TAKEDOWN DIRT RACER Gold",
    "XUSPKBC": "Hunter TAKEDOWN DIRT RACER Platinum",
    "PUSRC01": "Carson 500 GT Finish 1",
    "PUSRCA2": "Carson 500 GT Finish 2",
    "PUSRCA3": "Carson 500 GT Finish 3",
    "PUSRC0G": "Carson 500 GT Gold",
    "PUSRC0C": "Carson 500 GT Platinum",
    "XUSRCB1": "Carson RACING 500 GT Finish 1",
    "XUSRCB2": "Carson RACING 500 GT Finish 2",
    "XUSRCB3": "Carson RACING 500 GT Finish 3",
    "XUSRCBG": "Carson RACING 500 GT Gold",
    "XUSRCBC": "Carson RACING 500 GT Platinum",
    "PUSRN01": "Hunter RACING OVAL CHAMP Finish 1",
    "PUSRNA2": "Hunter RACING OVAL CHAMP Finish 2",
    "PUSRNA3": "Hunter RACING OVAL CHAMP Finish 3",
    "PUSRN0G": "Hunter RACING OVAL CHAMP Gold",
    "PUSRN0C": "Hunter RACING OVAL CHAMP Platinum",
    "PDLCMOR": "Hunter OVAL STEEL RACER Finish 1",
    "PDLCML2": "Hunter OVAL STEEL RACER Finish 2",
    "PDLCML3": "Hunter OVAL STEEL RACER Finish 3",
    "XUSRNB1": "Hunter BRT OVAL CHAMP Finish 1",
    "XUSRNB2": "Hunter BRT OVAL CHAMP Finish 2",
    "XUSRNB3": "Hunter BRT OVAL CHAMP Finish 3",
    "XUSRNBG": "Hunter BRT OVAL CHAMP Gold",
    "XUSRNBC": "Hunter BRT OVAL CHAMP Platinum",
    "PSPBEST": "Hunter BESTBUY OVAL CHAMP",
    "PUSMC04": "Carson GT CONCEPT Finish 1",
    "PUSM4A2": "Carson GT CONCEPT Finish 2",
    "PUSM4A3": "Carson GT CONCEPT Finish 3",
    "PUSM04G": "Carson GT CONCEPT Gold",
    "PUSM04C": "Carson GT CONCEPT Platinum",
    "PBTTMC04": "Carson TIGER GT Finish 1",
    "PBTTMC2": "Carson TIGER GT Finish 2",
    "PBTTMC3": "Carson TIGER GT Finish 3",
    "XUSM4B1": "Carson GT FLAME Finish 1",
    "XUSM4B2": "Carson GT FLAME Finish 2",
    "XUSM4B3": "Carson GT FLAME Finish 3",
    "XUSM4BG": "Carson GT FLAME Gold",
    "XUSM4BC": "Carson GT FLAME Platinum",
    "CARBMC04": "Carson CARBON GT CONCEPT",
    "PSPMETL": "Carson 'STEEL WHEELS' GT",
    "PUSCCO01": "Hunter CITIZEN Finish 1",
    "PUSCCOA2": "Hunter CITIZEN Finish 2",
    "PUSCCOA3": "Hunter CITIZEN Finish 3",
    "PUSCCO0G": "Hunter CITIZEN Gold",
    "PUSCCO0C": "Hunter CITIZEN Platinum",
    "XUSCCOB1": "Hunter CIVILIAN Finish 1",
    "XUSCCOB2": "Hunter CIVILIAN Finish 2",
    "XUSCCOB3": "Hunter CIVILIAN Finish 3",
    "XUSCCOBG": "Hunter CIVILIAN Gold",
    "XUSCCOBC": "Hunter CIVILIAN Platinum",
    "PEURR01": "Watson 25 V16 REVENGE Finish 1",
    "PEURRA2": "Watson 25 V16 REVENGE Finish 2",
    "PEURRA3": "Watson 25 V16 REVENGE Finish 3",
    "PEURR0G": "Watson 25 V16 REVENGE Gold",
    "PEURR0C": "Watson 25 V16 REVENGE Platinum",
    "XEURRB1": "Watson REVENGE RACER Finish 1",
    "XEURRB2": "Watson REVENGE RACER Finish 2",
    "XEURRB3": "Watson REVENGE RACER Finish 3",
    "XEURRBG": "Watson REVENGE RACER Gold",
    "XEURRBC": "Watson REVENGE RACER Platinum",
    "PEUS01": "Montgomery HAWKER Finish 1",
    "PEUSA2": "Montgomery HAWKER Finish 2",
    "PEUSA3": "Montgomery HAWKER Finish 3",
    "PEUS0G": "Montgomery HAWKER Gold",
    "PEUS0C": "Montgomery HAWKER Platinum",
    "XEUSB1": "Montgomery HAWKER SOLO Finish 1",
    "XEUSB2": "Montgomery HAWKER SOLO Finish 2",
    "XEUSB3": "Montgomery HAWKER SOLO Finish 3",
    "XEUSBG": "Montgomery HAWKER SOLO Gold",
    "XEUSBC": "Montgomery HAWKER SOLO Platinum",
    "CARBRWDS": "Montgomery CARBON HAWKER",
    "PEURG01": "Krieger ÜBERSCHALL 8 Finish 1",
    "PEUGTB2": "Krieger ÜBERSCHALL 8 Finish 2",
    "PEUGTB3": "Krieger ÜBERSCHALL 8 Finish 3",
    "PEURG0G": "Krieger ÜBERSCHALL 8 Gold",
    "PEURG0C": "Krieger ÜBERSCHALL 8 Platinum",
    "XEURG1BG": "Krieger ÜBERSCHALL CLEAR-VIEW Gold",
    "XEURG1BC": "Krieger ÜBERSCHALL CLEAR-VIEW Platinum",
    "CARBEAGT": "Krieger CARBON ÜBERSCHALL 8",
    "PSPT": "Krieger TARGET ÜBERSCHALL 8",
    "PUSCL01": "Carson THUNDER CUSTOM Finish 1",
    "PUSCL1A2": "Carson THUNDER CUSTOM Finish 2",
    "PUSCL1A3": "Carson THUNDER CUSTOM Finish 3",
    "PUSCL0G": "Carson THUNDER CUSTOM Gold",
    "PUSCL0C": "Carson THUNDER CUSTOM Platinum",
    "XUSCL1B1": "Carson THUNDER SHADOW Finish 1",
    "XUSCL1BG": "Carson THUNDER SHADOW Gold",
    "XUSCL1BC": "Carson THUNDER SHADOW Platinum",
    "PUSBH01": "Carson HOT ROD COUPE Finish 1",
    "PUSBHA2": "Carson HOT ROD COUPE Finish 2",
    "PUSBHA3": "Carson HOT ROD COUPE Finish 3",
    "PUSBH0G": "Carson HOT ROD COUPE Gold",
    "PUSBH0C": "Carson HOT ROD COUPE Platinum",
    "XUSBHB1": "Carson TRIBAL SPECIAL Finish 1",
    "XUSBHB2": "Carson TRIBAL SPECIAL Finish 2",
    "XUSBHB3": "Carson TRIBAL SPECIAL Finish 3",
    "XUSBHBG": "Carson TRIBAL SPECIAL Gold",
    "XUSBHBC": "Carson TRIBAL SPECIAL Platinum",
    "PSPCIR": "Carson CIRCUIT CITY HOT ROD",
    "PUSRI01": "Krieger RACING WTR Finish 1",
    "PUSRIA2": "Krieger RACING WTR Finish 2",
    "PUSRIA3": "Krieger RACING WTR Finish 3",
    "PUSRI0G": "Krieger RACING WTR Gold",
    "PUSRI0C": "Krieger RACING WTR Platinum",
    "PUSCPI5": "Krieger PCPD SPECIAL Finish 1",
    "PUSCPI3": "Krieger PCPD SPECIAL Finish 2",
    "PUSCPI4": "Krieger PCPD SPECIAL Finish 3",
    "PUSCPIG": "Krieger PCPD SPECIAL Gold",
    "PUSCPIC": "Krieger PCPD SPECIAL Platinum",
    "PSPWAL": "Krieger WALMART WTR",
    "PBTSVK01": "Hunter OLYMPUS Finish 1",
    "PDSVK0B": "Hunter OLYMPUS Finish 2",
    "PDSVK0W": "Hunter OLYMPUS Finish 3",
    "PDRWT01": "Nakamura RAI-JIN TURBO Finish 1",
    "PDRWTL2": "Nakamura RAI-JIN TURBO Finish 2",
    "PDRWTL3": "Nakamura RAI-JIN TURBO Finish 3",
    "PUSMBST": "Nakamura FV1100 MALE",
    "PUSMBS2": "Nakamura FV1100 FEMALE",
    "PUSMBSTG": "Nakamura FV1100-TI MALE-CHROME",
    "PUSMBS2G": "Nakamura FV1100-TI FEMALE-CHROME",
    "PUSMBSS1": "Nakamura FIREHAWK V4 MALE",
    "PUSMBSS2": "Nakamura FIREHAWK V4 FEMALE",
    "PUSMBSSG": "Nakamura FIREHAWK V4-TI MALE-CHROME",
    "PUSMBSG2": "Nakamura FIREHAWK V4-TI FEMALE-CHROME",
    "PUSMB01": "Nakamura FIREHAWK GP MALE",
    "PUSMB02": "Nakamura FIREHAWK GP FEMALE",
    "PUSMB1G": "Nakamura FIREHAWK GP-TI MALE-CHROME",
    "PUSMB2G": "Nakamura FIREHAWK GP-TI FEMALE-CHROME",
    "PUSMBGP1": "Nakamura FIREHAWK GP COMPETITION UNITED KINGDOM",
    "PUSMBG12": "Nakamura FIREHAWK GP COMPETITION JAPAN",
    "PUSMBG13": "Nakamura FIREHAWK GP COMPETITION USA",
    "PUSMBG14": "Nakamura FIREHAWK GP COMPETITION CANADA",
    "PUSMBG15": "Nakamura FIREHAWK GP COMPETITION ITALY",
    "PUSMBG16": "Nakamura FIREHAWK GP COMPETITION GERMANY",
    "PUSMBG17": "Nakamura FIREHAWK GP COMPETITION FRANCE",
    "PUSMBG18": "Nakamura FIREHAWK GP COMPETITION SPAIN",
    "PSDMC01": "Carson TOY CAVALRY",
    "PSDMC04": "Carson TOY GT CONCEPT",
    "PSDRI01": "Krieger TOY WTR",
    "PSDSC01": "Jansen TOY P12",
    "PSDBC01": "Hunter TOY MANHATTAN",
    "PSDPK01": "Hunter TOY TAKEDOWN 4X4",
    "PSDCCO01": "Hunter TOY CITIZEN",
    "PSDCV01": "Carson TOY INFERNO",
    "PSDGP": "Nakamura TOY FIREHAWK GP",
    "PDLCB2F": "Jansen P12 88 SPECIAL",
    "PDLCGB": "Hunter MANHATTAN SPIRIT",
    "PDLCNR01": "Carson GT NIGHTHAWK",
    "PDLCGL": "Hunter CAVALRY BOOTLEGGER",
    "PDSHR01": "Carson EXTREME HOT ROD",
    "PBTHM01": "Montgomery HAWKER MECH Finish 1",
    "PBTHM0B": "Montgomery HAWKER MECH Finish 2",
    "PBTHM0C": "Montgomery HAWKER MECH Finish 3",
    "PCCMC01": "Hunter PCPD CAVALRY",
    "PCCCLT2": "Hunter PCPD MESQUITE",
    "PCCBSC01": "Nakamura PCPD SI-7",
    "PCCCO01": "Hunter PCPD VEGAS",
    "PCCSV01": "Krieger PCPD PIONEER",
    "PCCBS01": "Nakamura PCPD IKUSA GT",
    "PCCBCC01": "Kitano PCPD HYDROS CUSTOM",
    "PCCCT01": "Hunter PCPD RELIABLE CUSTOM",
    "PCCBR01": "Watson PCPD R-TURBO ROADSTER",
    "PCCLM01": "Rossolini PCPD LM CLASSIC",
    "PCCBC01": "Hunter PCPD MANHATTAN",
    "PCCMU3": "Carson PCPD FASTBACK",
    "PCCGA01": "Carson PCPD GRAND MARAIS",
    "PCCSR01": "Montgomery PCPD HYPERION",
    "PCCSC03": "Krieger PCPD 616 SPORT",
    "PCCME01": "Hunter PCPD SPUR",
    "PCCRC03": "Montgomery PCPD GT 2400",
    "PCCSC01": "Jansen PCPD P12",
    "PCCCV01": "Carson PCPD INFERNO VAN",
    "PCCSC02": "Rossolini PCPD TEMPESTA",
    "PCCLR01": "Carson PCPD OPUS",
    "PCCMC02": "Carson PCPD ANNIHILATOR",
    "PCCSC04": "Jansen PCPD X12",
    "PCCC01": "Kitano PCPD TOUGE SPORT",
    "PCCPK01": "Hunter PCPD TAKEDOWN 4X4",
    "PCCRC01": "Carson PCPD 500 GT",
    "PCCRN01": "Hunter PCPD RACING OVAL CHAMP",
    "PCCMC04": "Carson PCPD GT CONCEPT",
    "PCCRR01": "Watson PCPD 25 V16 REVENGE",
    "PCCS01": "Montgomery PCPD HAWKER",
    "PCCRG01": "Krieger PCPD ÜBERSCHALL 8",
    "PCCCC01": "Carson PCPD THUNDER CUSTOM",
    "PCCBH01": "Carson PCPD HOT ROD COUPE",
    "PCCSVK01": "Hunter PCPD OLYMPUS",
    "PCCRWT01": "Nakamura PCPD RAI-JIN TURBO",
    "PDDK01": "Carson DUST STORM Finish 1",
    "PDDK0A": "Carson DUST STORM Finish 2",
    "PDDK0C": "Carson DUST STORM Finish 3",
    "PDDK01XS": "Carson DUST STORM SUPERTURBO",
    "PBTJPDI": "Jansen P12 DIAMOND",
    "PBTSVK02": "Hunter OLYMPUS GOVERNOR",
    "PBTEA01": "Carson ANNIHILATOR STREET ROD Finish 1",
    "PBTEA1B": "Carson ANNIHILATOR STREET ROD Finish 2",
    "PBTEA1C": "Carson ANNIHILATOR STREET ROD Finish 3",
    "PSDGL01": "Hunter TOY BOOTLEGGER",
    "PSD88S": "Jansen TOY 88 SPECIAL",
    "PSDNR01": "Carson TOY NIGHTHAWK",
    "PSDGB": "Hunter TOY SPIRIT",
    "TUSRV01": "T_US_RV_01",
    "TUSRV02": "T_US_RV_02",
    "TUSLT01": "T_US_LargeTruck_01",
    "TUSLT02": "T_US_LargeTruck_02",
    "TUSLT03": "T_US_LargeTruck_03",
    "TUSLT04": "T_US_LargeTruck_04",
    "TUSLT07": "T_US_LargeTruck_07",
    "TUSLT08": "T_US_LargeTruck_08",
    "TUSLT09": "T_US_LargeTruck_09",
    "TUSAC01": "T_US_ArticCab_01",
    "TUSAC02": "T_US_ArticCab_02",
    "TUSSUV01": "T_US_SUV_01",
    "TUSSUV02": "T_US_SUV_02",
    "TUSDTT01": "T_US_DTTaxi_01",
    "TUSDTT1B": "T_US_DTTaxi_01B",
    "TEUMPV01": "T_EU_MPV_01",
    "TUSCC01": "T_US_Compact_01",
    "TASS01": "T_AS_Saloon_01",
    "TUSSL01": "T_US_Saloon_01",
    "TUSB01": "T_US_Bus_01",
    "TUSB02": "T_US_Bus_02",
    "TUSSV01": "T_US_SpecialVan_02",
    "TUSPK01": "T_US_Pickup_01",
    "TUSPK01B": "T_US_Pickup_01B",
    "TUSSW01": "T_US_Stationwagon_01",
    "TUSV01": "T_US_Van_01",
    "TUSV01B": "T_US_Van_01B",
    "TUSV02": "T_US_Van_02",
    "TUSV02B": "T_US_Van_02B",
    "TUSSV": "T_US_SponsorVan",
    "TUSGSV": "T_US_GilletteSponsorVan",
    "TUSSMT01": "T_US_SmallTruck_01",
    "TUSSMT02": "T_US_SmallTruck_02",
    "TUSSMT03": "T_US_SmallTruck_03",
    "TUSSMT04": "T_US_SmallTruck_04",
    "TUSTR01": "T_US_Trailer_01",
    "TUSTR02": "T_US_Trailer_02",
    "TUSTR03": "T_US_Trailer_03",
    "TUSTR04": "T_US_Trailer_04",
    "TUSTR05": "T_US_Trailer_05",
    "TUSTR06": "T_US_Trailer_06",
    "TUSLM01": "T_US_DTLimo_01",
    "PUSCVFA": "Carson HIPPY VAN",
    "PUSRNFA": "Hunter RACING OVAL CHAMP",
    "PBTCGT01": "UNKNOWN",
    "PBTHH01": "UNKNOWN",
    "PBTCFB01": "UNKNOWN",
    "PBTJP01": "UNKNOWN",
    "PBTKS01": "UNKNOWN",
    "PBTWRT01": "UNKNOWN",
    "PBTTHO01": "UNKNOWN",
    "PBTNI01": "UNKNOWN",
}